name: "Changelog entry checker"
inputs:
    ghToken:
        description: 'GitHub token'
        required: true
    username:
        description: 'Username for GitHub token user/app'
        required: false
        default: 'github-actions[bot]'
    requireLabel:
        description: 'If true then a T- label must be applied'
        required: false
        default: false
runs:
    using: 'docker'
    image: 'docker://ghcr.io/matrix-org/allchange:latest'
