name: "Changelog entry checker"
inputs:
    ghToken:
        description: 'GitHub token'
        required: true
    username:
        description: 'Username for GitHub token user/app'
        required: false
        default: 'github-actions[bot]'
    requireLabel:
        description: 'If true then one of "T-Deprecation", "T-Enhancement", "T-Defect", or "T-Task" labels must be present'
        required: false
        default: false
runs:
    using: 'docker'
    image: 'docker://ghcr.io/matrix-org/allchange:latest'
